defmodule EarWitness.CodeMySpec.Widget do
  @moduledoc """
  Public interface to a user's chat `WidgetClient`. Starts one Slipstream
  client per user on demand (under the app's DynamicSupervisor, keyed in the
  Registry) and exposes message send / pagination / state to `ChatWidgetLive`.
  Generated by `mix client_utils.gen.chat_widget`.
  """

  alias EarWitness.CodeMySpec.WidgetClient

  @registry EarWitness.CodeMySpec.WidgetRegistry
  @supervisor EarWitness.CodeMySpec.WidgetSupervisor

  @doc "Registry `:via` tuple for a user's client process."
  def via(user_id), do: {:via, Registry, {@registry, to_string(user_id)}}

  @doc """
  The single local user of this desktop install.

  There is no auth scope — identity is a UUID persisted in the config dir on
  first use, plus an optional operator-facing email from
  `config :ear_witness, :widget_user_email`.
  """
  def local_user do
    %{id: local_user_id(), email: local_user_email()}
  end

  defp local_user_id do
    path = Path.join(EarWitness.config_dir(), "widget_id")

    case File.read(path) do
      {:ok, id} when byte_size(id) > 0 ->
        String.trim(id)

      _ ->
        id = generate_uuid()
        File.mkdir_p!(EarWitness.config_dir())
        File.write!(path, id)
        id
    end
  end

  defp local_user_email do
    Application.get_env(:ear_witness, :widget_user_email) || "desktop-user@local"
  end

  defp generate_uuid do
    <<a::32, b::16, c::16, d::16, e::48>> = :crypto.strong_rand_bytes(16)

    :io_lib.format("~8.16.0b-~4.16.0b-~4.16.0b-~4.16.0b-~12.16.0b", [a, b, c, d, e])
    |> IO.iodata_to_binary()
  end

  @doc "PubSub topic ChatWidgetLive subscribes to for a user's message updates."
  def topic(user_id), do: "codemyspec:widget:#{user_id}"

  @doc "Starts the user's client if not already running. Idempotent."
  def ensure_started(user_id, user_email) do
    spec = {WidgetClient, [user_id: to_string(user_id), user_email: user_email]}

    case DynamicSupervisor.start_child(@supervisor, spec) do
      {:ok, pid} -> {:ok, pid}
      {:error, {:already_started, pid}} -> {:ok, pid}
      :ignore -> {:error, :not_configured}
      other -> other
    end
  end

  @doc "Current accumulated messages for the user (for a freshly-mounted widget)."
  def state(user_id) do
    GenServer.call(via(user_id), :state)
  catch
    :exit, _ -> %{messages: []}
  end

  def send_message(user_id, body), do: cast(user_id, {:send_message, body})
  def load_older(user_id, before), do: cast(user_id, {:load_older, before})

  @doc "Submit feedback (title/description/severity + optional screenshot) to CodeMySpec."
  def submit_feedback(user_id, payload), do: cast(user_id, {:submit_feedback, payload})

  defp cast(user_id, message) do
    GenServer.cast(via(user_id), message)
  catch
    :exit, _ -> :ok
  end
end
