defmodule EarWitness.CodeMySpec.WidgetClient do
  @moduledoc """
  Per-user Slipstream client bridging a logged-in user's chat widget to
  CodeMySpec.

  Connects **server-side** with the project deploy key (the key never reaches
  the browser), joins `conversation:<user_id>`, and relays messages between
  CodeMySpec and the user's `ChatWidgetLive` over local PubSub. Reconnects with
  backoff. Generated by `mix client_utils.gen.chat_widget`.
  """

  use Slipstream

  require Logger

  alias EarWitness.CodeMySpec.Widget

  def start_link(opts) do
    user_id = to_string(Keyword.fetch!(opts, :user_id))
    Slipstream.start_link(__MODULE__, Map.new(opts), name: Widget.via(user_id))
  end

  @impl Slipstream
  def init(opts) do
    user_id = to_string(opts.user_id)
    user_email = opts.user_email

    case build_uri(user_id, user_email) do
      {:ok, uri} ->
        socket =
          new_socket()
          |> assign(:user_id, user_id)
          |> assign(:user_email, user_email)
          |> assign(:topic, "conversation:#{user_id}")
          |> assign(:messages, [])
          |> assign(:reconnect_attempts, 0)
          |> connect!(uri: uri)

        {:ok, socket}

      {:error, reason} ->
        Logger.warning("[WidgetClient] cannot connect: #{inspect(reason)}")
        :ignore
    end
  end

  @impl Slipstream
  def handle_connect(socket) do
    {:ok, join(socket, socket.assigns.topic)}
  end

  @impl Slipstream
  def handle_join(_topic, _reply, socket) do
    {:ok, assign(socket, :reconnect_attempts, 0)}
  end

  @impl Slipstream
  def handle_message(_topic, "new_message", payload, socket) do
    messages = socket.assigns.messages ++ [payload]
    socket = assign(socket, :messages, messages)
    broadcast(socket, {:new_message, payload})
    {:ok, socket}
  end

  def handle_message(_topic, _event, _payload, socket), do: {:ok, socket}

  # Reply to a `load_older` push: prepend the previous page and re-broadcast.
  @impl Slipstream
  def handle_reply(_ref, {:ok, %{"messages" => older}}, socket) when is_list(older) do
    messages = older ++ socket.assigns.messages
    socket = assign(socket, :messages, messages)
    broadcast(socket, {:messages, messages})
    {:ok, socket}
  end

  def handle_reply(_ref, _reply, socket), do: {:ok, socket}

  @impl Slipstream
  def handle_call(:state, _from, socket) do
    {:reply, %{messages: socket.assigns.messages}, socket}
  end

  @impl Slipstream
  def handle_cast({:send_message, body}, socket) do
    push(socket, socket.assigns.topic, "send_message", %{"body" => body})
    {:noreply, socket}
  end

  def handle_cast({:load_older, before}, socket) do
    push(socket, socket.assigns.topic, "load_older", %{"before" => before})
    {:noreply, socket}
  end

  # Feedback rides the same deploy-key connection as chat — pushed to CodeMySpec
  # as a `submit_feedback` event on the conversation topic.
  def handle_cast({:submit_feedback, payload}, socket) do
    push(socket, socket.assigns.topic, "submit_feedback", payload)
    {:noreply, socket}
  end

  @impl Slipstream
  def handle_disconnect(reason, socket) do
    attempts = socket.assigns.reconnect_attempts
    delay = backoff(attempts)
    Logger.info("[WidgetClient] disconnected (#{inspect(reason)}), reconnecting in #{delay}ms")
    Process.send_after(self(), :reconnect, delay)
    {:ok, assign(socket, :reconnect_attempts, attempts + 1)}
  end

  @impl Slipstream
  def handle_info(:reconnect, socket) do
    case build_uri(socket.assigns.user_id, socket.assigns.user_email) do
      {:ok, uri} ->
        {:ok, socket} = connect(socket, uri: uri)
        {:noreply, socket}

      {:error, _reason} ->
        Process.send_after(self(), :reconnect, backoff(socket.assigns.reconnect_attempts))
        {:noreply, socket}
    end
  end

  defp broadcast(socket, message) do
    Phoenix.PubSub.broadcast(
      EarWitness.PubSub,
      Widget.topic(socket.assigns.user_id),
      message
    )
  end

  defp backoff(attempts), do: min(trunc(:math.pow(2, attempts) * 1000), 10_000)

  # The deploy key is self-identifying on CodeMySpec (blind index), so the
  # widget presents only the key — no project id.
  defp build_uri(user_id, user_email) do
    base = Application.get_env(:ear_witness, :codemyspec_widget_url)
    deploy_key = Application.get_env(:ear_witness, :deploy_key)

    if present?(base) and present?(deploy_key) do
      query =
        URI.encode_query(%{
          "deploy_key" => deploy_key,
          "user_id" => user_id,
          "user_email" => user_email,
          "vsn" => "2.0.0"
        })

      {:ok, "#{base}/websocket?#{query}"}
    else
      {:error, :not_configured}
    end
  end

  defp present?(nil), do: false
  defp present?(""), do: false
  defp present?(_), do: true
end
