defmodule EarWitness.CodeMySpec.Widget do
  @moduledoc """
  Public interface to a user's chat `WidgetClient`. Starts one Slipstream
  client per user on demand (under the app's DynamicSupervisor, keyed in the
  Registry) and exposes message send / pagination / state to `ChatWidgetLive`.
  Generated by `mix client_utils.gen.chat_widget`.
  """

  alias EarWitness.CodeMySpec.WidgetClient

  @registry EarWitness.CodeMySpec.WidgetRegistry
  @supervisor EarWitness.CodeMySpec.WidgetSupervisor

  @doc "Registry `:via` tuple for a user's client process."
  def via(user_id), do: {:via, Registry, {@registry, to_string(user_id)}}

  @doc """
  The single local user of this desktop install.

  There is no auth scope — identity is a UUID persisted in the config dir on
  first use, plus an operator-facing email.

  The email is the conversation key on the CodeMySpec side (a conversation is
  looked up by `(account, project, email)`), so it MUST be unique per install —
  otherwise every desktop install would collapse into one shared thread. When
  the operator supplies a real address via `config :ear_witness,
  :widget_user_email` we use it; otherwise we synthesize a stable,
  install-unique address from the persisted UUID (`<uuid>@desktop.earwitness.local`).
  """
  def local_user do
    id = local_user_id()
    %{id: id, email: local_user_email(id)}
  end

  defp local_user_id do
    path = Path.join(EarWitness.config_dir(), "widget_id")

    case File.read(path) do
      {:ok, id} when byte_size(id) > 0 ->
        String.trim(id)

      _ ->
        id = generate_uuid()
        File.mkdir_p!(EarWitness.config_dir())
        File.write!(path, id)
        id
    end
  end

  defp local_user_email(id) do
    Application.get_env(:ear_witness, :widget_user_email) || "#{id}@desktop.earwitness.local"
  end

  defp generate_uuid do
    <<a::32, b::16, c::16, d::16, e::48>> = :crypto.strong_rand_bytes(16)

    :io_lib.format("~8.16.0b-~4.16.0b-~4.16.0b-~4.16.0b-~12.16.0b", [a, b, c, d, e])
    |> IO.iodata_to_binary()
  end

  @doc "PubSub topic ChatWidgetLive subscribes to for a user's message updates."
  def topic(user_id), do: "codemyspec:widget:#{user_id}"

  @doc "Starts the user's client if not already running. Idempotent."
  def ensure_started(user_id, user_email) do
    spec = {WidgetClient, [user_id: to_string(user_id), user_email: user_email]}

    case DynamicSupervisor.start_child(@supervisor, spec) do
      {:ok, pid} -> {:ok, pid}
      {:error, {:already_started, pid}} -> {:ok, pid}
      :ignore -> {:error, :not_configured}
      other -> other
    end
  end

  @doc "Current accumulated messages for the user (for a freshly-mounted widget)."
  def state(user_id) do
    GenServer.call(via(user_id), :state)
  catch
    :exit, _ -> %{messages: []}
  end

  @doc """
  Best-effort registration of this install as an `external_user` on CodeMySpec.

  Chat and issue reporting do NOT depend on this — the conversation is created
  on the fly at join time. This purely populates CodeMySpec's durable user
  roster (with platform/version metadata) so support has context. Fired once
  when the widget client starts; failures are logged and swallowed so a
  down/unreachable CodeMySpec never affects the local app.

  POSTs `{"user": {email, external_id, name, metadata}}` to the widget REST
  scope with the project deploy key as a Bearer token — same auth as the
  outbound Slipstream socket, still outbound-only.
  """
  def register_user do
    deploy_key = Application.get_env(:ear_witness, :deploy_key)
    base = Application.get_env(:ear_witness, :codemyspec_widget_url)

    if present?(deploy_key) and present?(base) do
      user = local_user()

      body = %{
        user: %{
          email: user.email,
          external_id: user.id,
          name: "EarWitness Desktop",
          metadata: install_metadata()
        }
      }

      Req.post(api_users_url(base),
        headers: [{"authorization", "Bearer #{deploy_key}"}],
        json: body,
        retry: false,
        receive_timeout: 5_000
      )
      |> case do
        {:ok, %{status: status}} when status in 200..299 -> :ok
        {:ok, %{status: status}} -> {:error, {:http_status, status}}
        {:error, reason} -> {:error, reason}
      end
    else
      {:error, :not_configured}
    end
  end

  defp install_metadata do
    %{
      platform: platform(),
      app_version: to_string(Application.spec(:ear_witness, :vsn))
    }
  end

  defp platform do
    case :os.type() do
      {:unix, :darwin} -> "macos"
      {:win32, _} -> "windows"
      {:unix, _} -> "linux"
      _ -> "unknown"
    end
  end

  # Derive the widget REST origin from the (websocket) widget URL:
  # wss://host[:port]/widget -> https://host[:port]/api/widget/users
  defp api_users_url(base) do
    uri = URI.parse(base)

    scheme =
      case uri.scheme do
        "wss" -> "https"
        "ws" -> "http"
        other -> other
      end

    port_part =
      if uri.port && uri.port not in [80, 443], do: ":#{uri.port}", else: ""

    "#{scheme}://#{uri.host}#{port_part}/api/widget/users"
  end

  defp present?(nil), do: false
  defp present?(""), do: false
  defp present?(_), do: true

  def send_message(user_id, body), do: cast(user_id, {:send_message, body})
  def load_older(user_id, before), do: cast(user_id, {:load_older, before})

  @doc "Submit feedback (title/description/severity + optional screenshot) to CodeMySpec."
  def submit_feedback(user_id, payload), do: cast(user_id, {:submit_feedback, payload})

  defp cast(user_id, message) do
    GenServer.cast(via(user_id), message)
  catch
    :exit, _ -> :ok
  end
end
