defmodule EarWitnessWeb.ChatWidgetLive do
  @moduledoc """
  Always-on support widget for logged-in users — a sticky nested LiveView with
  two tabs: **Chat** (live conversation with a CodeMySpec operator) and
  **Feedback** (report an issue, with an optional screenshot).

  Both tabs ride the same per-user `WidgetClient` Slipstream connection,
  authenticated by the project deploy key — the key never reaches the browser.
  Chat relays `send_message`/`new_message`; feedback pushes a `submit_feedback`
  event on the same conversation topic. Generated by
  `mix client_utils.gen.chat_widget`.

  The screenshot button uses a colocated hook that dynamically imports
  `html-to-image` — run `npm install html-to-image --prefix assets` to enable it
  (feedback still submits without a screenshot if it's absent).
  """

  use EarWitnessWeb, :live_view

  alias EarWitness.CodeMySpec.Widget

  @impl true
  def mount(_params, _session, socket) do
    # Desktop app, single local user — no auth scope; identity is a
    # persistent per-install id (see Widget.local_user/0).
    user = Widget.local_user()

    socket =
      socket
      |> assign(:user, user)
      |> assign(:open, false)
      |> assign(:tab, :chat)
      |> assign(:messages, [])
      |> assign(:fb_submitted, false)
      |> assign(:fb_error, nil)
      |> assign(:screenshot_data, nil)
      |> assign(:capturing, false)

    if connected?(socket) and user do
      Widget.ensure_started(user.id, user.email)
      Phoenix.PubSub.subscribe(EarWitness.PubSub, Widget.topic(user.id))
      %{messages: messages} = Widget.state(user.id)
      {:ok, assign(socket, :messages, messages), layout: false}
    else
      {:ok, socket, layout: false}
    end
  end

  @impl true
  def handle_event("toggle", _params, socket) do
    {:noreply, update(socket, :open, &(!&1))}
  end

  def handle_event("switch_tab", %{"tab" => tab}, socket) do
    {:noreply, assign(socket, :tab, tab_atom(tab))}
  end

  def handle_event("send", %{"message" => %{"body" => body}}, socket) do
    body = String.trim(body)

    if body != "" and socket.assigns.user do
      Widget.send_message(socket.assigns.user.id, body)
    end

    {:noreply, socket}
  end

  def handle_event("load_older", _params, socket) do
    with %{user: user} when not is_nil(user) <- socket.assigns,
         before when is_binary(before) <- oldest_cursor(socket.assigns.messages) do
      Widget.load_older(user.id, before)
    end

    {:noreply, socket}
  end

  def handle_event("capture_start", _params, socket) do
    {:noreply, assign(socket, :capturing, true)}
  end

  def handle_event("screenshot_captured", %{"data" => data_url}, socket) do
    {:noreply, socket |> assign(:screenshot_data, data_url) |> assign(:capturing, false)}
  end

  def handle_event("remove_screenshot", _params, socket) do
    {:noreply, assign(socket, :screenshot_data, nil)}
  end

  def handle_event("submit_feedback", params, socket) do
    title = String.trim(params["title"] || "")
    description = String.trim(params["description"] || "")
    severity = params["severity"] || "medium"

    cond do
      is_nil(socket.assigns.user) ->
        {:noreply, socket}

      title == "" ->
        {:noreply, assign(socket, :fb_error, "Title is required")}

      true ->
        payload = %{
          "title" => title,
          "description" => description,
          "severity" => severity,
          "screenshot" => socket.assigns.screenshot_data
        }

        Widget.submit_feedback(socket.assigns.user.id, payload)

        {:noreply,
         socket
         |> assign(:fb_submitted, true)
         |> assign(:fb_error, nil)
         |> assign(:screenshot_data, nil)}
    end
  end

  @impl true
  def handle_info({:new_message, payload}, socket) do
    {:noreply, assign(socket, :messages, socket.assigns.messages ++ [payload])}
  end

  def handle_info({:messages, messages}, socket) do
    {:noreply, assign(socket, :messages, messages)}
  end

  def handle_info(_message, socket), do: {:noreply, socket}

  defp oldest_cursor([%{"inserted_at" => ts} | _]), do: ts
  defp oldest_cursor(_), do: nil

  defp tab_atom("feedback"), do: :feedback
  defp tab_atom(_), do: :chat

  @impl true
  def render(assigns) do
    ~H"""
    <div
      :if={@user}
      id="codemyspec-chat-widget"
      phx-hook=".CmsScreenshot"
      class="fixed bottom-4 right-4 z-50"
    >
      <script :type={Phoenix.LiveView.ColocatedHook} name=".CmsScreenshot">
        export default {
          mounted() {
            this.el.addEventListener("click", async (e) => {
              if (!e.target.closest("[data-capture-screenshot]")) return
              this.pushEvent("capture_start", {})
              try {
                const { toPng } = await import("html-to-image")
                const dataUrl = await toPng(document.body, { cacheBust: true, pixelRatio: 1 })
                this.pushEvent("screenshot_captured", { data: dataUrl })
              } catch (err) {
                console.error("Screenshot capture failed:", err)
                this.pushEvent("screenshot_captured", { data: null })
              }
            })
          },
        }
      </script>

      <button
        type="button"
        phx-click="toggle"
        data-test="widget-toggle"
        class="btn btn-primary btn-circle shadow-lg"
        aria-label="Support"
      >
        💬
      </button>

      <div
        :if={@open}
        data-test="widget-panel"
        class="absolute bottom-16 right-0 flex max-h-[30rem] w-80 flex-col rounded-box border border-base-300 bg-base-100 shadow-xl"
      >
        <div role="tablist" class="tabs tabs-bordered shrink-0">
          <button
            role="tab"
            phx-click="switch_tab"
            phx-value-tab="chat"
            data-test="tab-chat"
            class={["tab", @tab == :chat && "tab-active"]}
          >
            Chat
          </button>
          <button
            role="tab"
            phx-click="switch_tab"
            phx-value-tab="feedback"
            data-test="tab-feedback"
            class={["tab", @tab == :feedback && "tab-active"]}
          >
            Feedback
          </button>
        </div>

        <div :if={@tab == :chat} data-test="chat-pane" class="flex min-h-0 flex-1 flex-col">
          <div data-test="chat-messages" class="flex-1 space-y-2 overflow-y-auto p-3">
            <button
              :if={@messages != []}
              type="button"
              phx-click="load_older"
              data-test="chat-load-older"
              class="btn btn-ghost btn-xs w-full"
            >
              Load older messages
            </button>

            <div
              :for={message <- @messages}
              data-test="chat-message"
              data-role={message["role"]}
              class={["chat", if(message["role"] == "user", do: "chat-end", else: "chat-start")]}
            >
              <div class="chat-bubble whitespace-pre-wrap break-words">{message["body"]}</div>
            </div>
          </div>

          <form phx-submit="send" data-test="chat-form" class="flex gap-2 border-t border-base-300 p-3">
            <input
              type="text"
              name="message[body]"
              data-test="chat-input"
              placeholder="Type a message…"
              autocomplete="off"
              class="input input-bordered input-sm flex-1"
            />
            <button type="submit" class="btn btn-primary btn-sm">Send</button>
          </form>
        </div>

        <div :if={@tab == :feedback} data-test="feedback-pane" class="min-h-0 flex-1 overflow-y-auto p-3">
          <div :if={@fb_submitted} class="py-6 text-center" data-test="feedback-thanks">
            <div class="mb-2 text-2xl text-success">✓</div>
            <p class="text-sm text-base-content/70">Thanks for your feedback!</p>
          </div>

          <form
            :if={!@fb_submitted}
            phx-submit="submit_feedback"
            data-test="feedback-form"
            class="space-y-3"
          >
            <div :if={@fb_error} class="alert alert-error p-2 text-xs">
              <span>{@fb_error}</span>
            </div>

            <div :if={@screenshot_data} class="relative">
              <img src={@screenshot_data} class="w-full rounded border border-base-300" />
              <button
                type="button"
                phx-click="remove_screenshot"
                class="btn btn-circle btn-error btn-xs absolute right-1 top-1"
              >
                ×
              </button>
            </div>

            <button
              :if={!@screenshot_data && @capturing}
              type="button"
              class="btn btn-ghost btn-xs w-full border-dashed border-base-300"
              disabled
            >
              <span class="animate-spin">⟳</span> Capturing…
            </button>
            <button
              :if={!@screenshot_data && !@capturing}
              type="button"
              data-capture-screenshot
              class="btn btn-ghost btn-xs w-full border-dashed border-base-300"
            >
              📷 Capture screenshot
            </button>

            <input
              type="text"
              name="title"
              data-test="feedback-title"
              placeholder="Brief summary"
              required
              class="input input-bordered input-sm w-full"
            />
            <textarea
              name="description"
              data-test="feedback-description"
              placeholder="Describe the issue…"
              rows="3"
              class="textarea textarea-bordered textarea-sm w-full"
            ></textarea>
            <select name="severity" class="select select-bordered select-sm w-full">
              <option value="low">Low</option>
              <option value="medium" selected>Medium</option>
              <option value="high">High</option>
              <option value="critical">Critical</option>
            </select>
            <button type="submit" class="btn btn-primary btn-sm w-full">Submit feedback</button>
          </form>
        </div>
      </div>
    </div>
    """
  end
end
